name: OWASP ZAP Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://d1gvejrxvpfna1.cloudfront.net'
