name: Ejecutar acciones basadas en el número de issue y comentario

on:
  issue_comment:
    types: [created]

jobs:
  acciones_condicionales:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # O la versión que necesites

      # Si es necesario instalar Jest
      - name: Instalar Jest Globalmente (opcional)
        if: contains(github.event.comment.body, '#listo') && github.event.issue.number == 44
        run: npm install -g jest

      # Ejecutar pruebas unitarias si el issue es el #44 y contiene #listo en el comentario
      - name: Ejecutar pruebas unitarias
        if: contains(github.event.comment.body, '#listo') && github.event.issue.number == 44
        run: |
          cd backend/lambda-listar-clientes
          npm install
          npm test
      
      # Mover la issue a la columna con ID 98236657 si los tests son exitosos
      - name: Mover issue a la columna deseada después de tests exitosos
        if: success() && contains(github.event.comment.body, '#listo') && github.event.issue.number == 44
        uses: actions/github-script@v5
        with:
          script: |
            const projectId = '3'; // Reemplaza esto con el ID real de tu proyecto
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Lista las columnas del proyecto
            const response = await github.rest.projects.listColumns({
              project_id: projectId,
              mediaType: {
                previews: [
                  'inertia' // Necesario para acceder a proyectos beta, quitar si es un proyecto clásico
                ]
              }
            });
            
            // Imprime las columnas encontradas
            console.log(response.data);
            
