name: Ejecutar acciones basadas en el número de issue y comentario

on:
  issue_comment:
    types: [created]

jobs:
  acciones_condicionales:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # O la versión que necesites

      # Opcionalmente instala Jest globalmente si es necesario para tu proyecto
      - name: Instalar Jest Globalmente (opcional)
        if: contains(github.event.comment.body, '#listo') && github.event.issue.number == 44
        run: npm install -g jest

      # Ejecutar pruebas unitarias si el issue es el #44 y contiene #listo en el comentario
      - name: Ejecutar pruebas unitarias
        if: contains(github.event.comment.body, '#listo') && github.event.issue.number == 44
        run: |
          cd backend/lambda-listar-clientes
          npm install
          npm test

      # Puedes agregar más pasos con diferentes condiciones para otros números de issue aquí
